behaviors:
  DriveCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 204800
      learning_rate: 5.0e-5
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.93
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000000
    time_horizon: 64
    summary_freq: 10000